server:
  port: 8762

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: st-cloud-eureka-client
