server:
  port: 9003
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
spring:
  application:
    name: st-cloud-zuul

zuul:
  routes:
    sa:
      path: /sa/**
      serviceId: ST-CLOUD-EUREKA-CLIENT
    sb:
      path: /sb/**
      serviceId: ST-CLOUD-RIBBON